server: 
    port: 8080
spring: 
   application: 
       name: eureka-provider
   cloud:
       config: 
           uri: http://127.0.0.1:8888
           name: springCloudApp
           profile: ${config.profile:dev}
eureka: 
    client: 
        serviceUrl:
            defaultZone: http://127.0.0.1:9999/eureka/