ribbon:
   #请求连接的超时时间
   ConnectTimeout: 3000
   #请求处理的超时时间
   ReadTimeout: 12000
   MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
   MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
   OkToRetryOnAllOperations: false  #是否所有操作都重试 

hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 60000

eureka: 
    client: 
        serviceUrl:
            defaultZone: http://127.0.0.1:9999/eureka/