server: 
    port: 8888
spring: 
    cloud: 
        config: 
            server: 
                git: 
                    uri: https://github.com/huohaitao/spring-cloud.git
                    searchPaths: repo
    application:
        name: spingCloudConfServer  