server: 
    port: 8888
spring: 
    cloud: 
        config: 
            server: 
                git: 
                    uri: https://github.com/fengzp/config/
                    searchPaths: demo*
                    username: huohaitao
                    password: hht521445
    application:
        name: spingCloudConfServer