server: 
    port: 8888
spring: 
   application:
        name: spingCloudConfServer
   cloud: 
       config: 
           server: 
               git: 
                   uri: https://github.com/huohaitao/spring-cloud.git
                   searchPaths: config/demo
                   #username: huohaitao
                   #password: hht521445